### ISSUE TITLE
Missing Ultravox

### ISSUE THREAD

**Issue by laubonghaudoi** [jishengpeng/WavChat#4]
https://github.com/fixie-ai/ultravox is a full-duplex dialogue LLM, currently the paper is missing it. We should include it as well?

**Comment by jishengpeng** [comment]
> https://github.com/fixie-ai/ultravox is a full-duplex dialogue LLM, currently the paper is missing it. We should include it as well?

Thank you very much for your valuable feedback. We will include the Ultravox update in future versions; however, it is likely that it will not be the primary focus, as it still appears to be a non-end-to-end spoken dialogue model. We appreciate your understanding and continued support.

**Comment by laubonghaudoi** [comment]
Yeah Ultravox is not e2e but its UX is very close to it, and it is one of the latest demonstrations of achieving low-latency with a cascading pipeline so I think it's worth including it. Thanks for the consideration!
